wip

diff --git a/.github/workflows/command.yml b/.github/workflows/command.yml
--- a/.github/workflows/command.yml
+++ b/.github/workflows/command.yml
@@ -46,7 +46,7 @@ jobs:
     outputs:
       meta_matrix: ${{ steps.set-matrix.outputs.meta_matrix }}
 
-  command_test:
+  command_test1:
     needs: [build-matrix]
     strategy:
       fail-fast: false
@@ -106,6 +106,36 @@ jobs:
       - name: Test Info
         run: |
           sudo META=${{matrix.meta}} .github/scripts/command/info.sh
+          
+      - name: Log
+        if: ${{ always() }}
+        run: |
+          echo "juicefs log"
+          sudo tail -n 1000 /var/log/juicefs.log
+          grep "<FATAL>:" /var/log/juicefs.log && exit 1 || true
+          
+      - name: Setup upterm session
+        if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug }}
+        # if: failure()
+        timeout-minutes: 60
+        uses: lhotari/action-upterm@v1
+
+  command_test2:
+    needs: [build-matrix]
+    strategy:
+      fail-fast: false
+      matrix:
+        # meta: [ 'sqlite3', 'redis', 'tikv']
+        meta: ${{ fromJson(needs.build-matrix.outputs.meta_matrix) }}
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 1
+
+      - name: Build 
+        uses: ./.github/actions/build
 
       - name: Test Sync
         timeout-minutes: 30
@@ -127,7 +157,7 @@ jobs:
 
   success-all-test:
     runs-on: ubuntu-latest
-    needs: [command_test]
+    needs: [command_test1, command_test2]
     if: always()
     steps:
       - uses: technote-space/workflow-conclusion-action@v3
