wip

diff --git a/.github/workflows/command.yml b/.github/workflows/command.yml
--- a/.github/workflows/command.yml
+++ b/.github/workflows/command.yml
@@ -49,7 +49,7 @@ jobs:
   command_test1:
     needs: [build-matrix]
     strategy:
-      fail-fast: false
+      fail-fast: true
       matrix:
         # meta: [ 'sqlite3', 'redis', 'tikv']
         meta: ${{ fromJson(needs.build-matrix.outputs.meta_matrix) }}
@@ -78,11 +78,6 @@ jobs:
         run: |
           sudo META=${{matrix.meta}} .github/scripts/command/config.sh
     
-      - name: Test Quota
-        timeout-minutes: 30
-        run: |
-          sudo META=${{matrix.meta}} .github/scripts/command/quota.sh 
-          
       - name: Test Clone
         timeout-minutes: 30
         run: |
@@ -106,7 +101,7 @@ jobs:
       - name: Test Info
         run: |
           sudo META=${{matrix.meta}} .github/scripts/command/info.sh
-          
+
       - name: Log
         if: ${{ always() }}
         run: |
@@ -123,9 +118,42 @@ jobs:
   command_test2:
     needs: [build-matrix]
     strategy:
-      fail-fast: false
+      fail-fast: true
       matrix:
-        # meta: [ 'sqlite3', 'redis', 'tikv']
+        meta: ${{ fromJson(needs.build-matrix.outputs.meta_matrix) }}
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 1
+
+      - name: Build 
+        uses: ./.github/actions/build
+
+      - name: Test Quota
+        timeout-minutes: 30
+        run: |
+          sudo META=${{matrix.meta}} .github/scripts/command/quota.sh 
+
+      - name: Log
+        if: ${{ always() }}
+        run: |
+          echo "juicefs log"
+          sudo tail -n 1000 /var/log/juicefs.log
+          grep "<FATAL>:" /var/log/juicefs.log && exit 1 || true
+          
+      - name: Setup upterm session
+        if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug }}
+        # if: failure()
+        timeout-minutes: 60
+        uses: lhotari/action-upterm@v1
+
+  command_test3:
+    needs: [build-matrix]
+    strategy:
+      fail-fast: true
+      matrix:
         meta: ${{ fromJson(needs.build-matrix.outputs.meta_matrix) }}
     runs-on: ubuntu-20.04
     steps:
@@ -154,10 +182,11 @@ jobs:
         # if: failure()
         timeout-minutes: 60
         uses: lhotari/action-upterm@v1
+      
 
   success-all-test:
     runs-on: ubuntu-latest
-    needs: [command_test1, command_test2]
+    needs: [command_test1, command_test2, command_test3]
     if: always()
     steps:
       - uses: technote-space/workflow-conclusion-action@v3
