CI: migrate upload artifact to v4 (#5570)
Co-authored-by: zhoucheng <zhoucheng@juicedata.io>

diff --git a/.github/workflows/fsrand.yml b/.github/workflows/fsrand.yml
--- a/.github/workflows/fsrand.yml
+++ b/.github/workflows/fsrand.yml
@@ -3,24 +3,24 @@ name: "fsrand"
 on:
   push:
     branches:
-    - main
-    - release**
+      - main
+      - release**
     paths:
-    - '**/fsrand.yml'
-    - '**/fs.py'
-    - '**/fs_test.py'
-    - '**/acl_test.py'
+      - "**/fsrand.yml"
+      - "**/fs.py"
+      - "**/fs_test.py"
+      - "**/acl_test.py"
   pull_request:
     branches:
-    - main
-    - release**
+      - main
+      - release**
     paths:
-    - '**/fsrand2.yml'
-    - '**/fs.py'
-    - '**/fs_test.py'
-    - '**/acl_test.py'
+      - "**/fsrand.yml"
+      - "**/fs.py"
+      - "**/fs_test.py"
+      - "**/acl_test.py"
   schedule:
-    - cron:  '0 16 * * 0'
+    - cron: "0 16 * * 0"
   workflow_dispatch:
     inputs:
       debug:
@@ -29,14 +29,14 @@ on:
         required: false
         default: false
 jobs:
-  fsrand2:
+  fsrand:
     timeout-minutes: 60
     strategy:
       fail-fast: false
       matrix:
-        meta: ['redis', 'mysql', 'tikv']
+        meta: ["redis", "mysql", "tikv"]
         # meta: ['redis']
-        
+
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -52,15 +52,15 @@ jobs:
           else
             echo "target=juicefs" >> $GITHUB_OUTPUT
           fi
-  
+
       - name: Build
         timeout-minutes: 10
         uses: ./.github/actions/build
-        with: 
+        with:
           target: ${{steps.vars.outputs.target}}
 
       - name: Prepare meta db
-        run: | 
+        run: |
           chmod +x .github/scripts/start_meta_engine.sh
           source .github/scripts/start_meta_engine.sh
           start_meta_engine ${{matrix.meta}}
@@ -68,7 +68,7 @@ jobs:
           create_database $meta_url
 
       - name: Install tool
-        run: | 
+        run: |
           sudo .github/scripts/apt_install.sh attr
           sudo pip install xattr
           sudo pip install minio
@@ -88,7 +88,7 @@ jobs:
             echo "<FATAL>: mount failed"
             exit 1
           fi
-          
+
       - name: Run Examples
         timeout-minutes: 10
         run: |
@@ -96,33 +96,40 @@ jobs:
           sudo -E python3 .github/scripts/hypo/acl_test.py
 
       - name: Download example database
-        uses: dawidd6/action-download-artifact@v2.24.3
+        timeout-minutes: 5
+        continue-on-error: true
+        uses: actions/download-artifact@v4
         with:
-          name: hypothesis-example-db
+          name: hypothesis-example-db-${{ matrix.meta }}
           path: .hypothesis/examples
-          if_no_artifact_found: warn
-          workflow_conclusion: completed
 
       - name: Test
-        timeout-minutes: 125
+        continue-on-error: true
+        timeout-minutes: 120
         run: |
-          timeout 7200 sudo -E LOG_LEVEL=WARNING python3 .github/scripts/hypo/fs.py 2>&1 | tee fsrand.log || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then echo test failed; exit $code; fi
+          sudo -E LOG_LEVEL=WARNING python3 .github/scripts/hypo/fs.py 2>&1 | tee fsrand.log
+
+      - name: check fsrand.log
+        if: always()
+        run: |
+          grep "AssertionError" fsrand.log && exit 1 || true
 
       - name: Upload example database
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         if: always()
         with:
-          name: hypothesis-example-db
+          include-hidden-files: true
+          name: hypothesis-example-db-${{ matrix.meta }}
           path: .hypothesis/examples
 
       - name: check fsrand.log
         if: always()
-        run: | 
+        run: |
           tail -500 fsrand.log
 
       - name: check juicefs.log
         if: always()
-        run: | 
+        run: |
           if [ -f ~/.juicefs/juicefs.log ]; then
             tail -300 ~/.juicefs/juicefs.log
             grep "<FATAL>:" ~/.juicefs/juicefs.log && exit 1 || true
@@ -134,13 +141,13 @@ jobs:
 
       - name: Setup upterm session
         if: failure() && (github.event.inputs.debug == 'true' || github.run_attempt != 1)
-        # if: failure() 
+        # if: failure()
         timeout-minutes: 60
         uses: lhotari/action-upterm@v1
 
   success-all-test:
     runs-on: ubuntu-latest
-    needs: [fsrand2]
+    needs: [fsrand]
     if: always()
     steps:
       - uses: technote-space/workflow-conclusion-action@v3
