test uploading small files to gateway

diff --git a/.github/workflows/gateway.yml b/.github/workflows/gateway.yml
--- a/.github/workflows/gateway.yml
+++ b/.github/workflows/gateway.yml
@@ -96,19 +96,22 @@ jobs:
           export MINIO_ROOT_PASSWORD=minioadmin
           ./juicefs format $meta_url $volume
           ./juicefs gateway $meta_url localhost:9000 &
+
           dd if=/dev/urandom of=file iflag=fullblock,count_bytes bs=4k count='1G' > /dev/null
           mkdir data
           for i in {1..5}; do
             cp file data/file_$i
-          done
-          
+          done          
           md5deep -lr data/ > sum.md5
-          ./mc alias set minio http://localhost:9000 minioadmin minioadmin --api S3v4
-          ./mc mb minio/$volume
-          ./mc cp --recursive data/  minio/$volume/data
+
+          ./juicefs sync --dirs data/  s3://minioadmin:minioadmin@localhost:9000/$volume/data/ --no-https -p 50
+          #./mc alias set minio http://localhost:9000 minioadmin minioadmin --api S3v4
+          #./mc mb minio/$volume
+          #./mc cp --recursive data/  minio/$volume/data
           
           ./juicefs mount -d $meta_url $mp
-          md5deep -lrX sum.md5 $mp/data/ && echo "check md5 succeed" || echo "check md5 failed"
+          count=$(md5deep -lrX sum.md5 || wc -l)
+          [ $count = 0 ] && echo "check md5 succeed" || echo "check md5 failed"
 
       - name: Setup upterm session
         if: ${{ failure() }}
