remove ob container

diff --git a/.github/workflows/gateway.yml b/.github/workflows/gateway.yml
--- a/.github/workflows/gateway.yml
+++ b/.github/workflows/gateway.yml
@@ -417,6 +417,7 @@ jobs:
       - uses: actions/checkout@v3
       - name: install ob
         run: |
+          docker rm obstandalone --force || echo "remove obstandalone failed"
           docker run -p 2881:2881 --name obstandalone -e MINI_MODE=1 -d oceanbase/oceanbase-ce
           mysql -h127.0.0.1 -P2881 -uroot -e "ALTER SYSTEM SET _ob_enable_prepared_statement=TRUE;" 
       - name: Test
@@ -442,6 +443,7 @@ jobs:
       - uses: actions/checkout@v3
       - name: install ob
         run: |
+          docker rm obstandalone --force || echo "remove obstandalone failed"
           docker run -p 2881:2881 --name obstandalone -e MINI_MODE=1 -d oceanbase/oceanbase-ce
           mysql -h127.0.0.1 -P2881 -uroot -e "ALTER SYSTEM SET _ob_enable_prepared_statement=TRUE;" 
       - name: Test
@@ -467,6 +469,7 @@ jobs:
       - uses: actions/checkout@v3
       - name: install ob
         run: |
+          docker rm obstandalone --force || echo "remove obstandalone failed"
           docker run -p 2881:2881 --name obstandalone -e MINI_MODE=1 -d oceanbase/oceanbase-ce
           mysql -h127.0.0.1 -P2881 -uroot -e "ALTER SYSTEM SET _ob_enable_prepared_statement=TRUE;" 
       - name: Test
