fix load

diff --git a/.github/workflows/load.yml b/.github/workflows/load.yml
--- a/.github/workflows/load.yml
+++ b/.github/workflows/load.yml
@@ -63,14 +63,13 @@ jobs:
 
       - name: Prepare meta db
         run: | 
-          sudo chmod +x .github/scripts/start_meta_engine.sh
+          chmod +x .github/scripts/start_meta_engine.sh
           source .github/scripts/start_meta_engine.sh
           start_meta_engine ${{matrix.meta}}
 
-      - name: Test
+      - name: Load and dump
         timeout-minutes: 30
         run: |
-          sudo chmod +x .github/scripts/start_meta_engine.sh
           source .github/scripts/start_meta_engine.sh
           meta_url=$(get_meta_url ${{matrix.meta}})
           create_database $meta_url
@@ -80,12 +79,66 @@ jobs:
           gzip -dk  2M_emtpy_files.dump.gz
           load_file=2M_emtpy_files.dump
           echo `date`, start load
-          sudo ./juicefs load $meta_url $load_file
+          ./juicefs load $meta_url $load_file
           echo `date`, finish load
           echo `date`, start dump
-          sudo ./juicefs dump $meta_url dump.json
+          ./juicefs dump $meta_url dump.json
           echo `date`, finish dump
-          sudo ./juicefs mount $meta_url $mount_point -d
+          ./juicefs mount $meta_url $mount_point -d
+          inode=$(df -i $mount_point | grep JuiceFS |awk -F" " '{print $3}')
+          if [ "$inode" -ne "2233313" ]; then 
+            echo "<FATAL>: inode error: $inode"
+            exit 1
+          fi
+
+      - name: Clear
+        run: | 
+          source .github/scripts/start_meta_engine.sh
+          meta_url=$(get_meta_url ${{matrix.meta}})
+          mp=/tmp/juicefs-load-test
+          volume=jfs
+          test -d $mp && ./juicefs umount -f $mp
+          ./juicefs status $meta_url && UUID=$(./juicefs status $meta_url | grep UUID | cut -d '"' -f 4) || echo "meta not exist"
+          if [ -n "$UUID" ];then
+            ./juicefs destroy --force $meta_url $UUID
+          fi
+          test -d /var/jfs/$volume && rm -rf /var/jfs/$volume || true
+        shell: bash
+
+      - name: Load and dump with big directory
+        timeout-minutes: 30
+        run: |
+          source .github/scripts/start_meta_engine.sh
+          meta_url=$(get_meta_url ${{matrix.meta}})
+          create_database $meta_url
+          echo meta_url is: $meta_url
+          mount_point=/tmp/juicefs-load-test
+          wget -q https://s.juicefs.com/static/bench/1M_emtpy_files_in_one_dir.dump.gz
+          gzip -dk  1M_emtpy_files_in_one_dir.dump.gz
+          load_file=1M_emtpy_files_in_one_dir.dump
+          echo `date`, start load
+          ./juicefs load $meta_url $load_file
+          echo `date`, finish load
+          echo `date`, start dump
+          ./juicefs dump $meta_url dump.json
+          echo `date`, finish dump
+          ./juicefs mount $meta_url $mount_point -d
+          df -i $mount_point
+          inode=$(df -i $mount_point | grep JuiceFS |awk -F" " '{print $3}')
+          if [ "$inode" -ne "1000003" ]; then 
+            echo "<FATAL>: inode error: $inode"
+            exit 1
+          fi
+
+      - name: List
+        timeout-minutes: 30
+        run: | 
+          mount_point=/tmp/juicefs-load-test
+          file_count=$(ls -l $mount_point/test/test-dir.0-0/mdtest_tree.0/ | wc -l)
+          if [ "$file_count" -ne "1000001" ]; then 
+            echo "<FATAL>: file_count error: $file_count"
+            exit 1
+          fi
 
       - name: log
         if: ${{ always() }}
