ltpfs

diff --git a/.github/workflows/ltpfsmanyclient.yml b/.github/workflows/ltpfsmanyclient.yml
--- a/.github/workflows/ltpfsmanyclient.yml
+++ b/.github/workflows/ltpfsmanyclient.yml
@@ -71,8 +71,9 @@ jobs:
           sudo ./runltp -d /juice/data2 -f fs_bind,fs_perms_simple,fsx,io,smoketest -C result_other_data2.log.failed -T result_other_data2.log.tconf -l result_other_data2.log &
           sudo ./runltp -d /tmp/jfs -f fs_bind,fs_perms_simple,fsx,io,smoketest -C result_other_tmp.log.failed -T result_other_tmp.log.tconf -l result_other_tmp.log | tee /tmp/result_other_tmp
           echo "check other result begin"
-          diff results/result_other_data1.log.failed results/result_other_data2.log.failed
-          diff results/result_other_data1.log.failed results/result_other_tmp.log.failed
+          if [ -f "/opt/ltp/results/result_other_data1.log.failed" ];then cat /opt/ltp/results/result_other_data1.log.failed;exit 1; fi
+          if [ -f "/opt/ltp/results/result_other_data2.log.failed" ];then cat /opt/ltp/results/result_other_data2.log.failed;exit 1; fi
+          if [ -f "/opt/ltp/results/result_other_tmp.log.failed" ];then cat /opt/ltp/results/result_other_tmp.log.failed;exit 1; fi
           echo "check other result end"
           sudo ./runltp -d /juice/data1 -f fs -C result_data1.log.failed -T result_data1.log.tconf -l result_data1.log
           sleep 60s
@@ -80,8 +81,9 @@ jobs:
           sleep 60s
           sudo ./runltp -d /tmp/jfs -f fs -C result_tmp.log.failed -T result_tmp.log.tconf -l result_tmp.log | tee /tmp/result_tmp
           echo "check fs result begin"
-          diff results/result_data1.log.failed results/result_data2.log.failed
-          diff results/result_data1.log.failed results/result_tmp.log.failed
+          if [ -f "/opt/ltp/results/result_data1.log.failed" ];then cat /opt/ltp/results/result_data1.log.failed;exit 1; fi
+          if [ -f "/opt/ltp/results/result_data2.log.failed" ];then cat /opt/ltp/results/result_data2.log.failed;exit 1; fi
+          if [ -f "/opt/ltp/results/result_tmp.log.failed" ];then cat /opt/ltp/results/result_tmp.log.failed;exit 1; fi
           echo "check fs result end"
 
 
