debug

diff --git a/.github/workflows/mutate-test.yml b/.github/workflows/mutate-test.yml
--- a/.github/workflows/mutate-test.yml
+++ b/.github/workflows/mutate-test.yml
@@ -234,9 +234,7 @@ jobs:
           mutation_dir=$(cat mutate.log | grep "Save mutations into" | awk -F' ' '{print $4}' | sed -e 's:"::g')
           echo "mutation dir is $mutation_dir"
           JOB_INDEX=$job_index JOB_TOTAL=$job_total MUTATE_ORIGINAL=$source_file MUTATION_DIR=$mutation_dir COVERAGE_FILE=mutest-cov.out TEST_FILE_NAME="$test_file" PACKAGE_PATH="$package_path" python3 .github/scripts/mutesting.py | tee -a mutesting.log
-          if [ ! -f mutesting.log ]; then
-            echo "mutesting.log not exist" && exit 1
-          fi
+          if [ $? != 0 ]; then echo "run mutesting.py failed" && exit 1; fi
           mutate_report=$(tail -1 mutesting.log)
           echo "mutate_report: $mutate_report"
           echo "mutate_report=$mutate_report" >> $GITHUB_ENV
@@ -261,7 +259,7 @@ jobs:
             Usage: https://github.com/juicedata/juicefs/blob/main/.github/scripts/how_to_use_mutate_test.md  
 
       - name: Setup upterm session
-        if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug == 'true' }}
+        # if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug == 'true' }}
         timeout-minutes: 60
         uses: lhotari/action-upterm@v1
 
