CI: fix bug of version compatible test. (#2689)

diff --git a/.github/workflows/version_compatible_hypo.yml b/.github/workflows/version_compatible_hypo.yml
--- a/.github/workflows/version_compatible_hypo.yml
+++ b/.github/workflows/version_compatible_hypo.yml
@@ -47,43 +47,22 @@ jobs:
         with:
           old_juicefs_version: '1.0.0'
 
-      - name: Send Slack Notification
-        if: ${{ failure() }}
-        uses: juicedata/slack-notify-action@main
-        with:
-          channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
-          slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"  
+      - name: Display log
+        if: ${{ always() }}
+        shell: bash
+        run: | 
+          if [ -f "/home/runner/.juicefs/juicefs.log" ]; then
+            cat /home/runner/.juicefs/juicefs.log
+            grep "<FATAL>:" /home/runner/.juicefs/juicefs.log && exit 1 || true
+          fi
 
-      # - name: Setup upterm session
-      #   if: ${{ failure() }}
-      #   timeout-minutes: 30
-      #   uses: lhotari/action-upterm@v1
-
-  test-1-0-0-rc2-redis:
-    runs-on: ubuntu-latest
-    services:
-      redis:
-        # Docker Hub image
-        image: redis
-        # Set health checks to wait until redis has started
-        options: >-
-          --health-cmd "redis-cli ping"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          # Maps port 6379 on service container to the host
-          - 6379:6379
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 1
-      
-      - name: Test
-        uses: ./.github/actions/version-compatible-hypo
-        with:
-          old_juicefs_version: '1.0.0-rc2'
+      - name: Display command
+        if: ${{ always() }}
+        shell: bash
+        run: | 
+          if [ -f "command.log" ]; then
+            tail -100 command.log
+          fi
 
       - name: Send Slack Notification
         if: ${{ failure() }}
@@ -97,76 +76,141 @@ jobs:
       #   timeout-minutes: 30
       #   uses: lhotari/action-upterm@v1
 
-  test-1-0-0-beta1-redis:
-    runs-on: ubuntu-latest
-    services:
-      redis:
-        # Docker Hub image
-        image: redis
-        # Set health checks to wait until redis has started
-        options: >-
-          --health-cmd "redis-cli ping"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          # Maps port 6379 on service container to the host
-          - 6379:6379
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 1
+  # test-1-0-0-rc2-redis:
+  #   runs-on: ubuntu-latest
+  #   services:
+  #     redis:
+  #       # Docker Hub image
+  #       image: redis
+  #       # Set health checks to wait until redis has started
+  #       options: >-
+  #         --health-cmd "redis-cli ping"
+  #         --health-interval 10s
+  #         --health-timeout 5s
+  #         --health-retries 5
+  #       ports:
+  #         # Maps port 6379 on service container to the host
+  #         - 6379:6379
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 1
       
-      - name: Test
-        uses: ./.github/actions/version-compatible-hypo
-        with:
-          old_juicefs_version: '1.0.0-beta1'
+  #     - name: Test
+  #       uses: ./.github/actions/version-compatible-hypo
+  #       with:
+  #         old_juicefs_version: '1.0.0-rc2'
 
-      - name: Send Slack Notification
-        if: ${{ failure() }}
-        uses: juicedata/slack-notify-action@main
-        with:
-          channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
-          slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"  
+  #     - name: Display log
+  #       if: ${{ always() }}
+  #       shell: bash
+  #       run: | 
+  #         if [ -f "/home/runner/.juicefs/juicefs.log" ]; then
+  #           cat /home/runner/.juicefs/juicefs.log
+  #           grep "<FATAL>:" /home/runner/.juicefs/juicefs.log && exit 1 || true
+  #         fi
+
+  #     - name: Send Slack Notification
+  #       if: ${{ failure() }}
+  #       uses: juicedata/slack-notify-action@main
+  #       with:
+  #         channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
+  #         slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"  
 
       # - name: Setup upterm session
       #   if: ${{ failure() }}
       #   timeout-minutes: 30
       #   uses: lhotari/action-upterm@v1
 
-  test-0-17-1-redis:
-    runs-on: ubuntu-latest
-    services:
-      redis:
-        # Docker Hub image
-        image: redis
-        # Set health checks to wait until redis has started
-        options: >-
-          --health-cmd "redis-cli ping"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          # Maps port 6379 on service container to the host
-          - 6379:6379
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 1
+  # test-1-0-0-beta1-redis:
+  #   runs-on: ubuntu-latest
+  #   services:
+  #     redis:
+  #       # Docker Hub image
+  #       image: redis
+  #       # Set health checks to wait until redis has started
+  #       options: >-
+  #         --health-cmd "redis-cli ping"
+  #         --health-interval 10s
+  #         --health-timeout 5s
+  #         --health-retries 5
+  #       ports:
+  #         # Maps port 6379 on service container to the host
+  #         - 6379:6379
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 1
       
-      - name: Test
-        uses: ./.github/actions/version-compatible-hypo
-        with:
-          old_juicefs_version: '0.17.1'
+  #     - name: Test
+  #       uses: ./.github/actions/version-compatible-hypo
+  #       with:
+  #         old_juicefs_version: '1.0.0-beta1'
 
-      - name: Send Slack Notification
-        if: ${{ failure() }}
-        uses: juicedata/slack-notify-action@main
-        with:
-          channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
-          slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"  
+  #     - name: Display log
+  #       if: ${{ always() }}
+  #       shell: bash
+  #       run: | 
+  #         if [ -f "/home/runner/.juicefs/juicefs.log" ]; then
+  #           cat /home/runner/.juicefs/juicefs.log
+  #           grep "<FATAL>:" /home/runner/.juicefs/juicefs.log && exit 1 || true
+  #         fi
+
+  #     - name: Send Slack Notification
+  #       if: ${{ failure() }}
+  #       uses: juicedata/slack-notify-action@main
+  #       with:
+  #         channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
+  #         slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"  
+
+      # - name: Setup upterm session
+      #   if: ${{ failure() }}
+      #   timeout-minutes: 30
+      #   uses: lhotari/action-upterm@v1
+
+  # test-0-17-1-redis:
+  #   runs-on: ubuntu-latest
+  #   services:
+  #     redis:
+  #       # Docker Hub image
+  #       image: redis
+  #       # Set health checks to wait until redis has started
+  #       options: >-
+  #         --health-cmd "redis-cli ping"
+  #         --health-interval 10s
+  #         --health-timeout 5s
+  #         --health-retries 5
+  #       ports:
+  #         # Maps port 6379 on service container to the host
+  #         - 6379:6379
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 1
+      
+  #     - name: Test
+  #       uses: ./.github/actions/version-compatible-hypo
+  #       with:
+  #         old_juicefs_version: '0.17.1'
+
+  #     - name: Display log
+  #       if: ${{ always() }}
+  #       shell: bash
+  #       run: | 
+  #         if [ -f "/home/runner/.juicefs/juicefs.log" ]; then
+  #           cat /home/runner/.juicefs/juicefs.log
+  #           grep "<FATAL>:" /home/runner/.juicefs/juicefs.log && exit 1 || true
+  #         fi
+
+  #     - name: Send Slack Notification
+  #       if: ${{ failure() }}
+  #       uses: juicedata/slack-notify-action@main
+  #       with:
+  #         channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
+  #         slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"  
 
       # - name: Setup upterm session
       #   if: ${{ failure() }}
